### ISSUE TITLE
System connection abort

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/WalletConnectKotlinV2#156] opened 2022-05-20 13:05 UTC
Sometimes WebSockets get closed. Especially after the aeroplane mode on and off toggle.

**Comment by jakobuid** [comment] 2022-05-23 10:31
Issue occurred:
- Pixel 6, Android 12

**Comment by TalhaAli00** [comment] 2022-06-09 02:52
This seems like an [issue with Scarlet](https://github.com/Tinder/Scarlet/issues/56) (apparently it was fixed in a previous version but is still reproducible). Since this is an edge case when going from turning on airplane mode and then turning it off, we will keep an eye out for this use-case and close the issue. 
One solution would be to replace Scarlet with Ktor. We would just need to find a solution where we can listen in on the state of the WS client. the [Ktor docs](https://ktor.io/docs/websocket.html#websocket-api) state that closing of a WS is noted by an exception

**Closed by TalhaAli00** 2022-06-09 02:52 UTC
Labels: bug
