### ISSUE TITLE
Pair not working

### ISSUE THREAD

**Issue by SafePalWallet** [WalletConnect/WalletConnectKotlinV2#553] opened 2022-12-24 04:34 UTC
Integrating WalletConnectV2, but I have encountered some problems and need some assistances

1. Install the wallet-release.apk with https://github.com/WalletConnect/WalletConnectKotlinV2/releases(Bom-1.1.0, Core-1.6.0, Sign-2.4.0)
2. Open "WC Wallet" and then scan the the QRCode which generate on the site https://react-app.walletconnect.com/ , but not work, then found some error message on the terminal board 

12-23 14:17:45.778  4975  5086 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))
12-23 14:17:45.880  4975  5090 I System.out: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
12-23 14:17:45.880  4975  5090 I System.out: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
12-23 14:17:45.880  4975  5090 I System.out: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
12-23 14:17:45.880  4975  5090 I System.out: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
12-23 14:17:45.880  4975  5090 I System.out: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
12-23 14:17:45.880  4975  5090 I System.out: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
12-23 14:17:45.880  4975  5090 I System.out: 	at java.lang.Thread.run(Thread.java:920)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
12-23 14:17:45.881  4975  5090 E WalletAccountsViewModel: 	at java.lang.Thread.run(Thread.java:920)

12-23 14:17:50.863  4975  5090 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))
12-23 14:17:55.944  4975  5087 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))
12-23 14:18:01.028  4975  5087 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))
12-23 14:18:06.111  4975  5085 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))
12-23 14:18:11.192  4975  5062 D WalletWalletDelegate: onConnectionStateChange(ConnectionState(isAvailable=false))

I'm pretty sure my mobile network is fine

But after seeing Message onConnectionStateChange(ConnectionState(isAvailable=false)) many times, I finally saw ConnectionState(isAvailable=true)
I guess there may be some problems with the sdk that cause

**Comment by Elyniss** [comment] 2023-01-02 13:54
Hi @SafePalWallet! It's a duplicate of https://github.com/WalletConnect/WalletConnectKotlinV2/issues/556. It will be tracked there.

**Closed by Elyniss** 2023-01-02 13:54 UTC
Labels: bug

**Comment by jakobuid** [comment] 2023-01-10 11:57
@SafePalWallet Could you please provide the device type and Android system?

**Comment by SafePalWallet** [comment] 2023-01-13 06:37
> @SafePalWallet Could you please provide the device type and Android system?

Device: Samsung( Galaxy F52 5G)
OS: Android 12
